Updated interactive functions Modified git setup to put user into in a local file that won't be synced with repo

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -11,46 +11,66 @@ set -e
 
 echo ''
 
+# Create default functions for interactive messages using solarized colors
+export TXT_NC=$(tput sgr 0)
+export TXT_bold=$(tput bold)
+export TXT_blue=$(tput setaf 33)
+export TXT_green=$(tput setaf 64)
+export TXT_orange=$(tput setaf 166)
+export TXT_red=$(tput setaf 124)
+
 # Interaction functions
-info () {
-  printf "  [ \033[00;34m..\033[0m ] $1"
+msg_info () {
+  printf "\r  ${TXT_bold}${TXT_blue}[ ... ]${TXT_NC} $1\n"
 }
 
-user () {
-  printf "\r  [ \033[0;33m?\033[0m ] $1 "
+msg_user () {
+  printf "\r  ${TXT_bold}${TXT_orange}[ ? ]${TXT_NC} $1 "
 }
 
-success () {
-  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+msg_success () {
+  printf "\r  ${TXT_bold}${TXT_green}[ OK ]${TXT_NC} $1\n"
 }
 
-fail () {
-  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+msg_fail () {
+  printf "\r  ${TXT_bold}${TXT_red}[ FAIL ]${TXT_NC} $1\n"
   echo ''
   exit
 }
 
 
+# Create local folder for private files
+if [ ! -d  "$DOTFILES_ROOT/local/" ]; then
+	mkdir -p "$DOTFILES_ROOT/local/"
+fi
+
+
 # Create basic gitconfig.symlink file if one doesn't already exits
 setup_gitconfig () {
-  if ! [ -f git/gitconfig.symlink ]
+	GIT_LOCAL="$DOTFILES_ROOT/local/gitconfig.local.symlink"
+	
+  if ! [ -f "$GIT_LOCAL" ]
   then
-    info 'setup gitconfig'
+    msg_info 'Setting up git'
 
-    git_credential='cache'
-    if [ "$(uname -s)" == "Darwin" ]
-    then
-      git_credential='osxkeychain'
-    fi
+    #git_credential='cache'
+    #if [ "$(uname -s)" == "Darwin" ]
+    #then
+    #  git_credential='osxkeychain'
+    #fi
 
-    user ' - What is your github author name?'
+    msg_user ' - What is your github author name?'
     read -e git_authorname
-    user ' - What is your github author email?'
+    msg_user ' - What is your github author email?'
     read -e git_authoremail
 
-    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.symlink.example > git/gitconfig.symlink
+    #sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.symlink.example > git/gitconfig.symlink
 
-    success 'gitconfig'
+		echo "[user]" > "$GIT_LOCAL"
+		echo "  name=\"$git_authorname\"" >> "$GIT_LOCAL"
+		echo "  email=\"$git_authoremail\"" >> "$GIT_LOCAL"
+
+    msg_success 'Git configured with local information'
   fi
 }
 
@@ -76,7 +96,7 @@ link_file () {
 
       else
 
-        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
+        msg_user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
         [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
         read -n 1 action
 
@@ -108,32 +128,32 @@ link_file () {
     if [ "$overwrite" == "true" ]
     then
       rm -rf "$dst"
-      success "removed $dst"
+      msg_success "removed $dst"
     fi
 
     if [ "$backup" == "true" ]
     then
       mv "$dst" "${dst}.backup"
-      success "moved $dst to ${dst}.backup"
+      msg_success "moved $dst to ${dst}.backup"
     fi
 
     if [ "$skip" == "true" ]
     then
-      success "skipped $src"
+      msg_success "skipped $src"
     fi
   fi
 
   if [ "$skip" != "true" ]  # "false" or empty
   then
     ln -s "$1" "$2"
-    success "linked $1 to $2"
+    msg_success "linked $1 to $2"
   fi
 }
 
 
 # Finds all the *.symlink files and runs links_file() on each
 install_dotfiles () {
-  info 'installing dotfiles'
+  msg_info 'Installing dotfiles'
 
   local overwrite_all=false backup_all=false skip_all=false
 
@@ -151,7 +171,7 @@ install_osx_defaults() {
 	local name="OS X defaults"
 
 	echo ""
-	user "Configure ${name}?: \n\
+	msg_user "Configure ${name}?: \n\
 	[y]es, [n]o?"
 	read -n 1 action
 
@@ -166,29 +186,29 @@ install_osx_defaults() {
   
 	if [ "$overwrite" == "true" ]
 	then
-		info "Setting ${name}"
+		msg_info "Setting ${name}"
 		
 		if source $DOTFILES_ROOT/osx/set-defaults
 		then
-			success "${name} set"
+			msg_success "${name} set"
 		else
-			fail "Error setting ${name}"
+			msg_fail "Error setting ${name}"
 		fi
 		
 	else
-      success "skipped ${name}"
+      msg_success "Skipped ${name}"
 	fi
 }
 
 
 # Install dependencies (Homebrew, etc.)
 install_dependencies() {
-	info "installing dependencies"
+	msg_info "Installing dependencies from bin/dot"
 	if source bin/dot #> /tmp/dotfiles-dot 2>&1
 	then
-		success "dependencies installed"
+		msg_success "Dependencies installed"
 	else
-		fail "error installing dependencies"
+		msg_fail "Error installing dependencies"
 	fi
 }
 
